
# Style ruleset begin

option.textwidth = 100
option.indent = 2
option.exclude_paths = [
  "test/utils.svh",
] # this file contains a complex macro that svlint chokes on

# textrules.style_textwidth = true
textrules.style_semicolon = true
syntaxrules.tab_character = true
syntaxrules.style_indent = true
syntaxrules.multiline_if_begin = true
syntaxrules.multiline_for_begin = true
syntaxrules.style_trailingwhitespace = true
textrules.style_directives = true
syntaxrules.style_operator_arithmetic = true
syntaxrules.style_operator_boolean = true
syntaxrules.style_operator_integer = true
syntaxrules.style_operator_unary = true
syntaxrules.style_operator_arithmetic_leading_space = true
syntaxrules.style_operator_boolean_leading_space = true
syntaxrules.style_operator_integer_leading_space = true

syntaxrules.style_keyword_0or1space = true
syntaxrules.style_keyword_0space = true
syntaxrules.style_keyword_1or2space = true
syntaxrules.style_keyword_1space = true
syntaxrules.style_keyword_construct = true
syntaxrules.style_keyword_datatype = false  # overly restrictive.
syntaxrules.style_keyword_end = true
syntaxrules.style_keyword_maybelabel = true
syntaxrules.style_keyword_new = true
syntaxrules.style_keyword_newline = true
syntaxrules.style_commaleading = true
syntaxrules.eventlist_or = true

# Style ruleset end

# from designintents.toml
syntaxrules.blocking_assignment_in_always_ff = true
syntaxrules.blocking_assignment_in_always_latch = true
syntaxrules.non_blocking_assignment_in_always_comb = true
syntaxrules.case_default = true
syntaxrules.enum_with_type = true
syntaxrules.function_with_automatic = true
syntaxrules.keyword_forbidden_priority = true
syntaxrules.keyword_forbidden_unique = true
syntaxrules.keyword_forbidden_unique0 = true
# TODO syntaxrules.operator_case_equality = true
syntaxrules.procedural_continuous_assignment = true
syntaxrules.action_block_with_side_effect = true
# TODO syntaxrules.default_nettype_none = true
syntaxrules.function_same_as_system_function = true
# TODO syntaxrules.keyword_forbidden_always = true
# TODO syntaxrules.keyword_forbidden_wire_reg = true
syntaxrules.module_nonansi_forbidden = true
syntaxrules.generate_case_with_label = true
syntaxrules.generate_for_with_label = true
syntaxrules.generate_if_with_label = true
syntaxrules.localparam_type_twostate = true
syntaxrules.parameter_type_twostate = true
syntaxrules.localparam_explicit_type = true
# TODO syntaxrules.parameter_explicit_type = true
syntaxrules.parameter_default_value = true
syntaxrules.parameter_in_generate = true
syntaxrules.parameter_in_package = true
syntaxrules.genvar_declaration_in_loop = true
syntaxrules.genvar_declaration_out_loop = false
syntaxrules.keyword_forbidden_generate = true
syntaxrules.keyword_required_generate = false
# TODO syntaxrules.explicit_case_default = true
# TODO syntaxrules.explicit_if_else = true
syntaxrules.loop_statement_in_always_comb = true
syntaxrules.loop_statement_in_always_ff = true
syntaxrules.loop_statement_in_always_latch = true
syntaxrules.sequential_block_in_always_comb = true
syntaxrules.sequential_block_in_always_ff = true
syntaxrules.sequential_block_in_always_latch = true
syntaxrules.inout_with_tri = true
# TODO syntaxrules.input_with_var = true
# TODO syntaxrules.output_with_var = true
syntaxrules.interface_port_with_modport = true
